/**
 * apps/web/content/en.ts
 * English copy — single source of truth for all user-facing strings.
 * Key pattern: SCREEN_COMPONENT_ELEMENT
 * NO hardcoded strings in components — always reference from here.
 */

export const en = {
  // ── Global ─────────────────────────────────────────────────────────────
  GLOBAL_BRAND_NAME: 'ParkSafe',
  GLOBAL_TAGLINE: 'Anonymous vehicle communication',
  GLOBAL_PRIVACY_NOTICE: 'Your identity stays private — the vehicle owner will never see your number.',
  GLOBAL_ERROR_GENERIC: 'Something went wrong. Please try again.',
  GLOBAL_ERROR_NETWORK: 'Network error. Check your connection and try again.',
  GLOBAL_ERROR_RETRY_CTA: 'Try again',
  GLOBAL_LOADING: 'Loading…',
  GLOBAL_UPDATING: 'Updating…',
  GLOBAL_PRIVACY_BADGE_DEFAULT: 'Anonymous & private',
  GLOBAL_SITE_URL: 'https://parksafe.tribly.ai',
  GLOBAL_BUY_URL: 'https://parksafe.tribly.ai/register',

  // ── Metadata ───────────────────────────────────────────────────────────
  META_DEFAULT_TITLE: 'ParkSafe — Anonymous Vehicle Communication',
  META_DEFAULT_DESCRIPTION:
    'Contact any vehicle owner anonymously in seconds. No app download. No personal info shared.',
  META_CONTACT_TITLE: 'Contact vehicle owner',
  META_CONTACT_DESCRIPTION: 'Anonymously contact a vehicle owner via ParkSafe.',
  META_SUCCESS_TITLE: 'Message delivered — ParkSafe',
  META_CONTACT_CHANNEL_TITLE: 'How to contact — ParkSafe',
  META_REGISTER_TITLE: 'Register your vehicle',
  META_REGISTER_DESCRIPTION: 'Fill in your vehicle details to get your unique QR code.',
  META_REGISTER_START_TITLE: 'Register with QR tag',
  META_REGISTER_START_DESCRIPTION: 'Scan your ParkSafe QR sticker to register your vehicle.',
  META_SIGN_IN_TITLE: 'Sign in',
  META_SIGN_IN_DESCRIPTION: 'Sign in to your ParkSafe account with your mobile number.',
  META_DASHBOARD_TITLE: 'Dashboard',
  META_DASHBOARD_DESCRIPTION: 'Your driving score, vehicles, alerts, and rewards.',
  META_PROFILE_TITLE: 'Profile',
  META_PROFILE_DESCRIPTION: 'Manage your ParkSafe account.',
  META_PROFILE_EDIT_TITLE: 'Account details',
  META_PROFILE_EDIT_DESCRIPTION: 'Update your name and email.',
  META_SETTINGS_TITLE: 'Settings',
  META_SETTINGS_DESCRIPTION: 'Notification and account preferences.',
  META_HELP_CONTACT_TITLE: 'Help & Contact',
  META_HELP_CONTACT_DESCRIPTION: 'Get help and contact ParkSafe support.',
  META_TERMS_TITLE: 'Terms of Service',
  META_TERMS_DESCRIPTION: 'Terms and conditions for using ParkSafe.',
  META_PRIVACY_TITLE: 'Privacy Policy',
  META_PRIVACY_DESCRIPTION: 'How ParkSafe collects, uses, and protects your personal data.',
  META_VEHICLES_TITLE: 'Active vehicles',
  META_VEHICLES_DESCRIPTION: 'Manage your registered ParkSafe vehicles.',
  META_ALERTS_RECEIVED_TITLE: 'Alerts received',
  META_ALERTS_RECEIVED_DESCRIPTION: 'Parking and vehicle alerts sent to your vehicles.',
  META_ALERTS_SENT_TITLE: 'Alerts sent',
  META_ALERTS_SENT_DESCRIPTION: 'Alerts you sent to other vehicle owners.',
  META_VERIFY_OTP_TITLE: 'Verify OTP',
  META_ADMIN_TITLE: 'Admin — QR Tag Generator',
  META_ADMIN_DESCRIPTION: 'Generate bulk ParkSafe QR tags with unique IDs for sticker printing.',

  // ── Accessibility labels ─────────────────────────────────────────────────
  ARIA_MESSAGE_DELIVERED: 'Message delivered successfully',
  ARIA_GO_BACK: 'Go back',
  ARIA_DISMISS_ERROR: 'Dismiss error',
  ARIA_OTP_GROUP: 'One-time password input',
  ARIA_CLOSE_DIALOG: 'Close dialog',
  ARIA_PRIVACY_NOTICE: 'Privacy protection notice',
  ARIA_NOTIFICATION_PREFS: 'Notification preferences',
  ARIA_VEHICLES_LIST: 'Your vehicles',
  ARIA_KEY_FEATURES: 'Key features',
  ARIA_PRIVACY_INDICATOR: 'Privacy indicator',
  ARIA_EMERGENCY_CALL: 'Call emergency services at 112',

  // ── Landing Page ────────────────────────────────────────────────────────
  LANDING_HERO_HEADLINE: 'Contact any vehicle owner. Anonymously.',
  LANDING_HERO_SUBHEADING: 'No app download. No personal info shared. Just scan and send.',
  LANDING_HERO_CTA_PRIMARY: 'Get ParkSafe for your car',
  LANDING_HERO_CTA_SECONDARY: 'How it works',
  LANDING_SIGN_IN_CTA: 'Sign In',
  SIGN_IN_PAGE_TITLE: 'Sign in',
  SIGN_IN_HEADING: 'Welcome back',
  SIGN_IN_SUBTITLE: 'Enter your mobile number to receive a one-time code',
  SIGN_IN_CHANGE_PHONE: 'Use a different number',
  SIGN_IN_NO_ACCOUNT: 'New to ParkSafe?',
  SIGN_IN_REGISTER_LINK: 'Register your vehicle',
  SIGN_IN_NOT_REGISTERED_TITLE: 'This number is not registered with ParkSafe',
  SIGN_IN_NOT_REGISTERED_BODY:
    'Only mobile numbers linked to a registered vehicle can sign in. Scan your ParkSafe QR tag to register.',
  LANDING_TRUST_ANONYMOUS_LABEL: '100% Anonymous',
  LANDING_TRUST_ANONYMOUS_DESC: 'Neither party ever sees the other\'s number',
  LANDING_TRUST_INSTANT_LABEL: 'Instant Delivery',
  LANDING_TRUST_INSTANT_DESC: 'SMS + WhatsApp delivered in seconds',
  LANDING_TRUST_NOCALLS_LABEL: 'No Unwanted Calls',
  LANDING_TRUST_NOCALLS_DESC: 'Owners control which channels are enabled',
  LANDING_PLACEHOLDER_TITLE: 'How It Works, Pricing & FAQ sections',
  LANDING_PLACEHOLDER_BODY: 'Pull Figma design → implement pixel-perfect components here',

  // ── Contact Flow ────────────────────────────────────────────────────────
  CONTACT_PAGE_TITLE: 'Contact Owner',
  CONTACT_STEP_ISSUE: 'Step 1 of 2',
  CONTACT_STEP_CHANNEL: 'Step 2 of 2',
  CONTACT_BACK_TO_ISSUES: 'Back to issues',

  VEHICLE_CARD_ARIA: '{make} {model}, {colour}, plate {plate}',
  CONTACT_ANONYMITY_BANNER_TITLE: '🔒 Anonymous & Secure',
  CONTACT_ANONYMITY_BANNER_BODY: 'Your info stays private and is never shared',

  CONTACT_ISSUE_GRID_TITLE: 'What\'s the issue?',
  CONTACT_ISSUE_GRID_SUBTITLE:
    'Select the reason you need to contact this vehicle owner',

  CONTACT_ISSUE_CARD_BLOCKING_LABEL: 'Blocking my vehicle',
  CONTACT_ISSUE_CARD_BLOCKING_DESC: 'Vehicle is blocking my spot',
  CONTACT_ISSUE_CARD_WRONG_PARKING_LABEL: 'Wrong parking spot',
  CONTACT_ISSUE_CARD_WRONG_PARKING_DESC: 'Parked in my assigned spot',
  CONTACT_ISSUE_CARD_LIGHTS_ON_LABEL: 'Lights are ON',
  CONTACT_ISSUE_CARD_LIGHTS_ON_DESC: 'Headlights left on',
  CONTACT_ISSUE_CARD_DOOR_OPEN_LABEL: 'Door left open',
  CONTACT_ISSUE_CARD_DOOR_OPEN_DESC: 'Door or window open',
  CONTACT_ISSUE_CARD_FLAT_TYRE_LABEL: 'Flat tire',
  CONTACT_ISSUE_CARD_FLAT_TYRE_DESC: 'Tire appears flat',
  CONTACT_ISSUE_CARD_FLUID_LEAKING_LABEL: 'Fluid leaking',
  CONTACT_ISSUE_CARD_FLUID_LEAKING_DESC: 'Leaking oil or fluids',
  CONTACT_ISSUE_CARD_DAMAGE_LABEL: 'Vehicle damage',
  CONTACT_ISSUE_CARD_DAMAGE_DESC: 'Accident or damage occurred',
  CONTACT_ISSUE_CARD_EMERGENCY_LABEL: 'Emergency',
  CONTACT_ISSUE_CARD_EMERGENCY_DESC: 'Urgent attention needed',

  CONTACT_SELECTED_ISSUE_LABEL: 'Selected Issue',

  CONTACT_CHANNEL_TITLE: 'How to contact?',
  CONTACT_CHANNEL_SMS_LABEL: 'Send Message',
  CONTACT_CHANNEL_SMS_DESC: 'Instant notification via SMS',
  CONTACT_CHANNEL_WHATSAPP_LABEL: 'Send on WhatsApp',
  CONTACT_CHANNEL_WHATSAPP_DESC: 'Instant notification via WhatsApp',
  CONTACT_CHANNEL_CALL_LABEL: 'Call Owner',
  CONTACT_CHANNEL_CALL_DESC: 'Anonymous • Your number hidden',
  CONTACT_CHANNEL_CALL_DISABLED: 'Call not enabled by owner',
  CONTACT_CHANNEL_SMS_DISABLED: 'SMS not enabled by owner',
  CONTACT_CHANNEL_WHATSAPP_DISABLED: 'WhatsApp not enabled by owner',
  CONTACT_CHANNEL_NONE_AVAILABLE:
    'No contact methods are available for this vehicle right now.',

  CONTACT_PRIVACY_FOOTER_TITLE: 'Your Privacy is Protected',
  CONTACT_PRIVACY_FOOTER_BODY:
    'Your contact information remains completely anonymous. The vehicle owner will never see your number.',
  CONTACT_PRIVACY_BADGE_ANONYMOUS: '100% Anonymous',
  CONTACT_PRIVACY_BADGE_SECURE: 'Secure Communication',
  CONTACT_PRIVACY_BADGE_NO_SPAM: 'No Spam',

  CONTACT_ERROR_RATE_LIMIT: 'Please wait before contacting this vehicle again.',
  CONTACT_ERROR_CHANNEL_DISABLED: 'This contact method is not available.',
  CONTACT_ERROR_DELIVERY_FAILED: 'Failed to deliver your message. Please try again.',
  CONTACT_ERROR_OFFLINE: 'You appear to be offline. Check your connection and try again.',

  CONTACT_NOTE_LABEL: 'Add a note (optional)',
  CONTACT_NOTE_PLACEHOLDER: 'e.g. Your car is blocking my driveway on the left side.',
  CONTACT_NOTE_CHAR_COUNT: '{count}/140',

  CONTACT_SEND_CTA: 'Send message',
  CONTACT_SEND_LOADING: 'Sending…',

  CONTACT_SUCCESS_TITLE: '✓ Message Delivered',
  CONTACT_SUCCESS_BODY_SMS: 'The vehicle owner has been notified via SMS.',
  CONTACT_SUCCESS_BODY_WHATSAPP: 'The vehicle owner has been notified via WhatsApp.',
  CONTACT_SUCCESS_BODY_CALL: 'The vehicle owner has been notified via phone call.',
  CONTACT_SUCCESS_ALERT_LABEL: 'Alert sent',
  CONTACT_SUCCESS_SENT_BADGE: 'Sent',
  CONTACT_SUCCESS_BACK_HOME: 'Back to Home',
  CONTACT_SUCCESS_SEND_ANOTHER_ALERT: 'Send another alert',

  CONTACT_TAG_NOT_ACTIVATED_TITLE: 'Tag not activated',
  CONTACT_TAG_NOT_ACTIVATED_BODY: 'This ParkSafe tag hasn\'t been registered yet.',
  CONTACT_TAG_NOT_ACTIVATED_CTA: 'Register vehicle',
  CONTACT_TAG_INACTIVE_TITLE: 'Tag temporarily inactive',
  CONTACT_TAG_INACTIVE_BODY: 'The vehicle owner has paused notifications on this tag.',

  // ── OTP ────────────────────────────────────────────────────────────────
  OTP_SCREEN_TITLE: 'Verify your number',
  OTP_SCREEN_SUBTITLE: 'We\'ll send a one-time code to {phone}.',
  OTP_PHONE_LABEL: 'Mobile number',
  OTP_PHONE_PLACEHOLDER: '+91 98765 00000',
  OTP_SEND_CTA: 'Send OTP',
  OTP_SENDING: 'Sending…',
  OTP_ENTER_LABEL: 'Enter the 6-digit code',
  OTP_VERIFY_CTA: 'Verify',
  OTP_VERIFYING: 'Verifying…',
  OTP_RESEND_CTA: 'Resend OTP',
  OTP_RESEND_WAIT: 'Resend in {seconds}s',
  OTP_ERROR_EXPIRED: 'OTP expired or not requested.',
  OTP_ERROR_INCORRECT: 'Incorrect OTP. {attempts} attempt{plural} remaining.',
  OTP_ERROR_LOCKED: 'Too many attempts. Try again in {minutes} minutes.',
  VERIFY_OTP_BODY: 'We\'ll send a one-time code to your registered number.',
  VERIFY_OTP_PLACEHOLDER_TITLE: 'OTP input form',
  VERIFY_OTP_PLACEHOLDER_BODY: 'Uses OtpInput component from components/shared',

  // ── Registration ────────────────────────────────────────────────────────
  REGISTER_BRAND_WORDMARK: 'park safe',
  REGISTER_START_TITLE: 'Register your vehicle',
  REGISTER_START_HEADING: 'Scan your ParkSafe QR tag',
  REGISTER_START_BODY:
    'Point your phone camera at the QR code on your ParkSafe sticker. We\'ll open registration automatically.',
  REGISTER_START_STEPS_TITLE: 'How to register',
  REGISTER_START_STEP_LABEL: 'Step {step}',
  REGISTER_START_STEP_1: 'Open your phone\'s camera app',
  REGISTER_START_STEP_2: 'Aim at the QR code on your ParkSafe sticker',
  REGISTER_START_STEP_3: 'Tap the link and complete your vehicle details',
  REGISTER_START_NO_TAG_TITLE: 'Don\'t have a ParkSafe tag yet?',
  REGISTER_START_NO_TAG_BODY:
    'Order a ParkSafe QR sticker for your windshield. Peel, stick, and scan to register in under a minute.',
  REGISTER_START_BUY_CTA: 'Get ParkSafe QR tag',
  REGISTER_START_SIGN_IN_PROMPT: 'Already registered?',
  REGISTER_START_SIGN_IN_LINK: 'Sign in',
  REGISTER_PAGE_TITLE: 'Register Your Vehicle',
  REGISTER_PAGE_SUBTITLE: 'Fill in your vehicle details to get your unique QR code',
  REGISTER_SECTION_VEHICLE: 'Vehicle Details',
  REGISTER_SECTION_OWNER: 'Owner Details',
  REGISTER_SECTION_EMERGENCY: 'Emergency Contact',
  REGISTER_SECTION_CONSENT: 'Consent',
  REGISTER_VEHICLE_NUMBER_LABEL: 'Vehicle Number',
  REGISTER_VEHICLE_NUMBER_PLACEHOLDER: 'AP 01 AB 1234',
  REGISTER_VEHICLE_BRAND_LABEL: 'Vehicle Brand',
  REGISTER_VEHICLE_BRAND_PLACEHOLDER: 'Honda, Toyota, Hero',
  REGISTER_VEHICLE_MODEL_LABEL: 'Vehicle Model',
  REGISTER_VEHICLE_MODEL_PLACEHOLDER: 'City, Fortuner, Splendor',
  REGISTER_VEHICLE_COLOR_LABEL: 'Vehicle Color',
  REGISTER_VEHICLE_COLOR_PLACEHOLDER: 'White, Black, Red',
  REGISTER_VEHICLE_TYPE_LABEL: 'Vehicle Type',
  REGISTER_VEHICLE_TYPE_PLACEHOLDER: 'Select vehicle type',
  REGISTER_VEHICLE_TYPE_CAR: 'Car',
  REGISTER_VEHICLE_TYPE_BIKE: 'Bike',
  REGISTER_VEHICLE_TYPE_SCOOTER: 'Scooter',
  REGISTER_VEHICLE_TYPE_TRUCK: 'Truck',
  REGISTER_VEHICLE_TYPE_OTHER: 'Other',
  REGISTER_OWNER_NAME_LABEL: 'Full Name',
  REGISTER_OWNER_NAME_PLACEHOLDER: 'Enter your full name',
  REGISTER_OWNER_PHONE_LABEL: 'Mobile Number',
  REGISTER_OWNER_PHONE_PLACEHOLDER: '9876543210',
  REGISTER_EMERGENCY_NAME_LABEL: 'Full Name',
  REGISTER_EMERGENCY_NAME_PLACEHOLDER: 'Enter emergency contact name',
  REGISTER_EMERGENCY_PHONE_LABEL: 'Mobile Number',
  REGISTER_EMERGENCY_PHONE_PLACEHOLDER: '9876543210',
  REGISTER_WHATSAPP_LABEL: 'WhatsApp notifications enabled',
  REGISTER_CONSENT_LABEL: 'I agree to be contacted only for vehicle-related issues',
  REGISTER_RESET_CTA: 'Reset',
  REGISTER_SUBMIT_CTA: 'Register Vehicle',
  REGISTER_SUBMITTING: 'Registering…',
  REGISTER_REQUIRED_SUFFIX: '*',
  REGISTER_PRIVACY_TITLE: 'Your Privacy is Our Priority',
  REGISTER_PRIVACY_BODY:
    'Your personal information is encrypted and secure. We never share your contact details with anyone. Only vehicle-related issues will reach you.',
  REGISTER_PRIVACY_BADGE_ANONYMOUS: '100% Anonymous',
  REGISTER_PRIVACY_BADGE_SECURE: 'Secure & Encrypted',
  REGISTER_PRIVACY_BADGE_NO_SPAM: 'No Spam',
  REGISTER_CLOSE_ARIA: 'Close registration',
  REGISTER_OTP_TITLE: 'Verify your number',
  REGISTER_OTP_SUBTITLE: 'Enter the 6-digit code sent to {phone}',
  REGISTER_OTP_RESEND: 'Resend OTP',
  REGISTER_OTP_RESEND_WAIT: 'Resend in {seconds}s',
  REGISTER_OTP_CANCEL: 'Cancel',
  REGISTER_SUCCESS_TITLE: 'You\'re all set!',
  REGISTER_SUCCESS_BODY: 'Your vehicle is registered. Stick your ParkSafe QR tag and you\'re protected.',
  REGISTER_SUCCESS_CTA: 'Go to dashboard',
  REGISTER_ERROR_PLATE: 'Enter a valid Indian license plate (e.g. MH02AB1234)',
  REGISTER_ERROR_SAME_PHONE: 'Emergency contact must use a different mobile number',
  REGISTER_ERROR_CONSENT: 'You must agree to be contacted for vehicle-related issues',

  // ── Dashboard ────────────────────────────────────────────────────────────
  DASHBOARD_PAGE_TITLE: 'Active vehicles',
  DASHBOARD_VEHICLES_SUBTITLE: 'Vehicles linked to your ParkSafe QR tags and alert settings.',
  DASHBOARD_VEHICLES_SUMMARY_ONE: '1 active vehicle',
  DASHBOARD_VEHICLES_SUMMARY_MANY: '{count} active vehicles',
  DASHBOARD_VEHICLES_INFO_TITLE: 'Each vehicle has its own QR tag',
  DASHBOARD_VEHICLES_INFO_BODY:
    'Alerts from other drivers are delivered to the vehicle linked to your tag. Manage notifications in Settings.',
  DASHBOARD_GREETING_REWARDING_LINE_1: '{name}, you\'re a thoughtful driver',
  DASHBOARD_GREETING_REWARDING_LINE_2: 'with no alerts on your vehicles.',
  DASHBOARD_GREETING_MILD_LINE_1: '{name}, just a gentle heads-up',
  DASHBOARD_GREETING_MILD_ALERTS_ONE: 'you have 1 alert to review.',
  DASHBOARD_GREETING_MILD_ALERTS_MANY: 'you have {count} alerts to review.',
  DASHBOARD_GREETING_CAUTIOUS_LINE_1: '{name}, let\'s stay mindful',
  DASHBOARD_GREETING_CAUTIOUS_LINE_2: 'you have {count} alerts on your vehicles.',
  DASHBOARD_SAFE_DAYS_LABEL: 'days with 0 issues on your vehicles',
  DASHBOARD_STAT_ACTIVE_VEHICLES: 'Active vehicles',
  DASHBOARD_STAT_ALERTS_RECEIVED: 'Alerts received',
  DASHBOARD_STAT_ALERTS_SENT: 'Alerts sent',
  DASHBOARD_STATS_ARIA: 'Dashboard statistics',
  DASHBOARD_REWARDS_TITLE: 'Rewards',
  DASHBOARD_REWARDS_COUNT: '{count}/{total} unlocked',
  DASHBOARD_QUICK_ACTIONS_ARIA: 'Quick actions',
  DASHBOARD_ACTION_REGISTER_TITLE: 'Register vehicle',
  DASHBOARD_ACTION_REGISTER_DESC: 'Scan your ParkSafe QR tag',
  DASHBOARD_ACTION_BUY_TITLE: 'Buy ParkSafe tag',
  DASHBOARD_ACTION_BUY_DESC: 'Get a new QR sticker',
  DASHBOARD_NAV_ARIA: 'Dashboard navigation',
  DASHBOARD_PROFILE_LINK: 'Profile',
  DASHBOARD_PROFILE_MENU_ARIA: 'Account menu',
  DASHBOARD_PROFILE_MENU_DESC: 'Edit your name and email',
  DASHBOARD_PROFILE_MENU_VERSION: 'Park Safe v1.0.0',
  DASHBOARD_PROFILE_GUEST_NAME: 'Driver',
  DASHBOARD_PROFILE_WELCOME_SUBTITLE: 'Manage your QR codes and vehicle settings',
  DASHBOARD_PROFILE_SECTION_ACCOUNT: 'Account',
  DASHBOARD_PROFILE_SECTION_SUPPORT: 'Support',
  DASHBOARD_PROFILE_SECTION_LEGAL: 'Legal',
  DASHBOARD_PROFILE_HELP_TITLE: 'Help & Contact',
  DASHBOARD_PROFILE_HELP_DESC: 'Get help and contact support',
  HELP_SUPPORT_EMAIL: 'support@parksafe.app',
  HELP_SUBTITLE: 'Find answers to common questions or reach our support team.',
  HELP_INFO_TITLE: 'How can we help?',
  HELP_INFO_BODY: 'Browse quick answers below. If you need more help, contact us by email.',
  HELP_FAQ_TITLE: 'Common questions',
  HELP_FAQ_Q1: 'How does anonymous contact work?',
  HELP_FAQ_A1:
    'When someone scans your ParkSafe QR tag, they can alert you without seeing your phone number — and you never see theirs.',
  HELP_FAQ_Q2: 'How do I register a new vehicle?',
  HELP_FAQ_A2:
    'From your dashboard, tap Register vehicle and scan the QR sticker on your windshield. Fill in your vehicle details to activate alerts.',
  HELP_FAQ_Q3: 'How do I change notification settings?',
  HELP_FAQ_A3:
    'Open Settings from your profile to turn SMS, WhatsApp, or product update emails on or off.',
  HELP_CONTACT_TITLE: 'Contact support',
  HELP_CONTACT_EMAIL_LABEL: 'Email',
  HELP_CONTACT_RESPONSE: 'We typically respond within 1 business day.',
  HELP_CONTACT_COPY: 'Copy email',
  HELP_CONTACT_COPIED: 'Email copied',
  HELP_CONTACT_CTA: 'Send an email',
  DASHBOARD_PROFILE_TERMS_TITLE: 'Terms of Service',
  DASHBOARD_PROFILE_TERMS_DESC: 'Read our terms and conditions',
  LEGAL_TERMS_SUBTITLE: 'Please read these terms carefully before using ParkSafe.',
  LEGAL_PRIVACY_SUBTITLE: 'How we collect, use, and protect your personal information.',
  DASHBOARD_PROFILE_PRIVACY_TITLE: 'Privacy Policy',
  DASHBOARD_PROFILE_PRIVACY_DESC: 'How we protect your data',
  DASHBOARD_SETTINGS_LINK: 'Settings',
  DASHBOARD_SETTINGS_MENU_DESC: 'Notifications and preferences',
  DASHBOARD_SIGN_OUT_DESC: 'Sign out of your account',
  DASHBOARD_PROFILE_TITLE: 'Profile',
  DASHBOARD_PROFILE_ACCOUNT_TITLE: 'Account details',
  DASHBOARD_PROFILE_EDIT_SUBTITLE: 'Update your name and email used across ParkSafe.',
  DASHBOARD_PROFILE_FIRST_NAME_LABEL: 'First name',
  DASHBOARD_PROFILE_LAST_NAME_LABEL: 'Last name',
  DASHBOARD_PROFILE_NAME_LABEL: 'Full name',
  DASHBOARD_PROFILE_EMAIL_LABEL: 'Email (optional)',
  DASHBOARD_PROFILE_EMAIL_PLACEHOLDER: 'you@example.com',
  DASHBOARD_PROFILE_SAVE: 'Save profile',
  DASHBOARD_PROFILE_SAVED: 'Profile updated',
  DASHBOARD_SETTINGS_TITLE: 'Settings',
  DASHBOARD_SETTINGS_SUBTITLE: 'Manage how ParkSafe notifies you about your vehicles.',
  DASHBOARD_SETTINGS_INFO_TITLE: 'Notification preferences',
  DASHBOARD_SETTINGS_INFO_BODY:
    'Choose how you want to be alerted when someone contacts your vehicles.',
  DASHBOARD_SETTINGS_SMS_LABEL: 'SMS alerts',
  DASHBOARD_SETTINGS_SMS_DESC: 'Receive SMS when someone contacts your vehicle',
  DASHBOARD_SETTINGS_WHATSAPP_LABEL: 'WhatsApp alerts',
  DASHBOARD_SETTINGS_WHATSAPP_DESC: 'Receive WhatsApp alerts for your vehicles',
  DASHBOARD_SETTINGS_MARKETING_LABEL: 'Product updates',
  DASHBOARD_SETTINGS_MARKETING_DESC: 'Occasional tips on safe parking and driving',
  DASHBOARD_ERROR_SESSION: 'Your session expired. Please sign in again.',
  DASHBOARD_ERROR_LOAD_TITLE: 'Could not load dashboard',
  DASHBOARD_ERROR_LOAD_BODY: 'Please refresh the page to try again.',
  DASHBOARD_TAG_STATUS_ACTIVE: 'Active',
  DASHBOARD_TAG_STATUS_INACTIVE: 'Inactive',
  DASHBOARD_TAG_TOGGLE_ACTIVATE: 'Activate notifications',
  DASHBOARD_TAG_TOGGLE_DEACTIVATE: 'Pause notifications',
  DASHBOARD_CONTACT_HISTORY_TITLE: 'Recent alerts',
  DASHBOARD_CONTACT_HISTORY_EMPTY: 'No alerts yet. Your vehicles are clear!',
  DASHBOARD_ALERTS_RECEIVED_SUBTITLE: 'Anonymous alerts from other drivers about your parked vehicles.',
  DASHBOARD_ALERTS_RECEIVED_SUMMARY_ONE: '1 alert received',
  DASHBOARD_ALERTS_RECEIVED_SUMMARY_MANY: '{count} alerts received',
  DASHBOARD_ALERTS_RECEIVED_SUMMARY_RECENT: 'Most recent {time}',
  DASHBOARD_ALERTS_RECEIVED_PRIVACY_TITLE: 'Reporter identity is hidden',
  DASHBOARD_ALERTS_RECEIVED_PRIVACY_BODY:
    'You only see the issue type and how they contacted you — never their phone number.',
  DASHBOARD_ALERTS_GROUP_TODAY: 'Today',
  DASHBOARD_ALERTS_GROUP_YESTERDAY: 'Yesterday',
  DASHBOARD_ALERTS_GROUP_THIS_WEEK: 'This week',
  DASHBOARD_ALERTS_GROUP_EARLIER: 'Earlier',
  DASHBOARD_ALERTS_EMERGENCY_BADGE: 'Urgent',
  DASHBOARD_ALERTS_UNKNOWN_TIME: 'Time unavailable',
  DASHBOARD_ALERTS_VEHICLE_UNKNOWN: 'Vehicle details unavailable',
  DASHBOARD_ALERTS_RECEIVED_EMPTY_TITLE: 'No alerts yet',
  DASHBOARD_ALERTS_RECEIVED_EMPTY_BODY: 'Your vehicles are clear! No alerts have been sent to you yet.',
  DASHBOARD_ALERTS_RECEIVED_EMPTY_CTA: 'Manage notification settings',
  DASHBOARD_ALERTS_RECEIVED_LIST_ARIA: 'Alerts received on your vehicles',
  DASHBOARD_ALERT_CHANNEL_SMS: 'SMS',
  DASHBOARD_ALERT_CHANNEL_WHATSAPP: 'WhatsApp',
  DASHBOARD_ALERT_CHANNEL_CALL: 'Phone call',
  DASHBOARD_ALERT_CHANNEL_UNKNOWN: 'Unknown channel',
  DASHBOARD_ALERTS_SENT_SUBTITLE: 'Alerts you sent to other vehicle owners via ParkSafe.',
  DASHBOARD_ALERTS_SENT_SUMMARY_ONE: '1 alert sent',
  DASHBOARD_ALERTS_SENT_SUMMARY_MANY: '{count} alerts sent',
  DASHBOARD_ALERTS_SENT_SUMMARY_RECENT: 'Most recent {time}',
  DASHBOARD_ALERTS_SENT_PRIVACY_TITLE: 'You stay anonymous',
  DASHBOARD_ALERTS_SENT_PRIVACY_BODY:
    'Vehicle owners only see the issue and how you contacted them — never your phone number.',
  DASHBOARD_ALERTS_SENT_EMPTY_TITLE: 'No alerts yet',
  DASHBOARD_ALERTS_SENT_EMPTY_BODY: 'When you send an alert via ParkSafe, it will appear here.',
  DASHBOARD_ALERTS_SENT_EMPTY_CTA: 'Contact a vehicle',
  DASHBOARD_ALERTS_SENT_LIST_ARIA: 'Alerts you sent',
  DASHBOARD_ALERT_VIA_CHANNEL: 'via {channel}',
  DASHBOARD_ADD_VEHICLE_CTA: 'Add vehicle',
  DASHBOARD_VEHICLE_MENU_ARIA: 'Actions for {vehicle}',
  DASHBOARD_VEHICLE_MAKE_INACTIVE: 'Make inactive',
  DASHBOARD_EMPTY_TITLE: 'No vehicles yet',
  DASHBOARD_EMPTY_BODY: 'Add your vehicle to get started with ParkSafe.',
  DASHBOARD_SIGN_OUT_CTA: 'Sign out',
  DASHBOARD_FOOTER_TAGLINE: 'Connect. Resolve. Move on.',
  DASHBOARD_FOOTER_COPYRIGHT: '© 2026, tribly tech pvt ltd.',

  // ── Offline ─────────────────────────────────────────────────────────────
  OFFLINE_TITLE: 'You\'re offline',
  OFFLINE_BODY: 'ParkSafe needs an internet connection to contact vehicle owners.',
  OFFLINE_EMERGENCY_CTA: 'Call Emergency: 112',
  OFFLINE_CACHED_HINT: 'Your last saved vehicle details will appear here when available.',

  // ── 404 ──────────────────────────────────────────────────────────────────
  NOT_FOUND_TITLE: 'Page not found',
  NOT_FOUND_BODY: 'The page you\'re looking for doesn\'t exist.',
  NOT_FOUND_CTA: 'Go home',

  // ── Admin (QR tag generation) ───────────────────────────────────────────
  ADMIN_PAGE_BADGE: 'Internal',
  ADMIN_PAGE_TITLE: 'QR Tag Generator',
  ADMIN_PAGE_SUBTITLE: 'Create unique QR stickers with IDs for printing and inventory tracking.',

  ADMIN_AUTH_TITLE: 'Admin access',
  ADMIN_AUTH_SUBTITLE: 'Enter your admin API key to continue.',
  ADMIN_AUTH_API_KEY_LABEL: 'API key',
  ADMIN_AUTH_API_KEY_PLACEHOLDER: 'Paste admin API key',
  ADMIN_AUTH_SUBMIT: 'Continue',
  ADMIN_AUTH_VERIFYING: 'Verifying…',
  ADMIN_AUTH_SIGN_OUT: 'Sign out',
  ADMIN_AUTH_ERROR_EMPTY: 'API key is required.',
  ADMIN_AUTH_ERROR_INVALID: 'Invalid API key. Check the value and try again.',
  ADMIN_AUTH_ERROR_NOT_CONFIGURED: 'Admin access is not configured on the server.',
  ADMIN_AUTH_ERROR_NETWORK: 'Could not reach the server. Check your connection.',

  ADMIN_GENERATE_TITLE: 'Generate tags',
  ADMIN_GENERATE_SUBTITLE: 'Each tag gets a unique UUID encoded in its QR code.',
  ADMIN_COUNT_LABEL: 'Number of tags',
  ADMIN_COUNT_HINT: 'Between 1 and {max} tags per batch.',
  ADMIN_GENERATE_CTA: 'Generate',
  ADMIN_GENERATING: 'Generating…',
  ADMIN_ERROR_MIN_COUNT: 'Enter at least 1 tag.',
  ADMIN_ERROR_MAX_COUNT: 'Maximum {max} tags per batch.',
  ADMIN_ERROR_BATCH_IN_PROGRESS: 'Wait for the current batch to finish before starting a new one.',
  ADMIN_ERROR_DOWNLOAD: 'Download failed. Try again.',

  ADMIN_BATCH_PROGRESS_TITLE: 'Generating {count} tags',
  ADMIN_BATCH_COUNT: '{completed} of {total}',
  ADMIN_STATUS_PENDING: 'Queued',
  ADMIN_STATUS_PROCESSING: 'Generating',
  ADMIN_STATUS_COMPLETED: 'Complete',
  ADMIN_STATUS_FAILED: 'Failed',
  ADMIN_ETA_CALCULATING: 'Estimating time…',
  ADMIN_ETA_DONE: 'Finishing up',
  ADMIN_ETA_SECONDS: '~{count}s remaining',
  ADMIN_ETA_MINUTES: '~{count} min remaining',

  ADMIN_DOWNLOAD_ZIP: 'Download ZIP',
  ADMIN_DOWNLOAD_PREPARING: 'Preparing download…',
  ADMIN_DOWNLOAD_INFO_TITLE: 'What\'s in the ZIP?',
  ADMIN_DOWNLOAD_INFO_QR: 'PNG QR codes in qr-codes/ — one file per tag.',
  ADMIN_DOWNLOAD_INFO_CSV: 'tag_inventory.csv with Tag ID, code, contact URL, and status.',
  ADMIN_DOWNLOAD_INFO_SHEETS: 'Import the CSV directly into Google Sheets for inventory.',

  ADMIN_HISTORY_TITLE: 'Recent batches',
  ADMIN_HISTORY_SUBTITLE: 'Previously generated tag batches.',
  ADMIN_HISTORY_TAGS: 'tags',
  ADMIN_HISTORY_EMPTY: 'No batches yet.',
  ADMIN_HISTORY_ERROR: 'Could not load batch history.',

  ADMIN_TAB_GENERATE: 'Generate',
  ADMIN_TAB_INVENTORY: 'Inventory',
  ADMIN_TABS_ARIA: 'Admin sections',

  ADMIN_INVENTORY_TITLE: 'Tag inventory',
  ADMIN_INVENTORY_SUBTITLE: 'Live counts from your database — generated, in stock, and sold.',
  ADMIN_INVENTORY_REFRESH: 'Refresh',
  ADMIN_INVENTORY_ERROR: 'Could not load inventory. Try again.',
  ADMIN_INVENTORY_GENERATED: 'Generated',
  ADMIN_INVENTORY_GENERATED_HINT: 'Total tags created in the system.',
  ADMIN_INVENTORY_STOCK: 'In stock',
  ADMIN_INVENTORY_STOCK_HINT: 'Unregistered tags — available for sale or distribution.',
  ADMIN_INVENTORY_SOLD: 'Sold',
  ADMIN_INVENTORY_SOLD_HINT: 'Registered by owners — active or inactive.',
  ADMIN_INVENTORY_SOLD_BREAKDOWN: '{active} active · {inactive} inactive',
  ADMIN_INVENTORY_UPDATED: 'Last updated {time}',
  ADMIN_INVENTORY_BATCHES_TITLE: 'By batch',
  ADMIN_INVENTORY_BATCHES_SUBTITLE: 'Stock breakdown for each generation run.',
  ADMIN_INVENTORY_BATCHES_EMPTY: 'No batches yet. Generate tags on the first tab.',
  ADMIN_INVENTORY_COL_DATE: 'Batch',
  ADMIN_INVENTORY_COL_GENERATED: 'Generated',
  ADMIN_INVENTORY_COL_STOCK: 'In stock',
  ADMIN_INVENTORY_COL_SOLD: 'Sold',
} as const

export type CopyKey = keyof typeof en
